apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tedx2020.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "tedx2020.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "tedx2020.fullname" . }}
    spec:
      containers:
      - name: {{ include "tedx2020.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: {{ include "tedx2020.fullname" . }}-secret
              key: mysql-host
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "tedx2020.fullname" . }}-secret
              key: mysql-user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "tedx2020.fullname" . }}-secret
              key: mysql-password
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ include "tedx2020.fullname" . }}-secret
              key: mysql-database
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: tedx-data
          mountPath: /app/tedxdata
      volumes:
      - name: tedx-data
        persistentVolumeClaim:
          claimName: {{ include "tedx2020.fullname" . }}-pvc

