apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tedx-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi  # This should match the size in the PV
  storageClassName: tedx-sc

