apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "tedx2020.fullname" . }}-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessModes | first }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClassName }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c9e89bd602ca1148::fsap-0b3007c646686e562

