apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tedx2020.fullname" . }}-pvc
spec:
  accessModes:
    - {{ .Values.persistence.accessModes | first }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClassName }}

