apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-user: {{ .Values.secret.mysqlUser }}
  mysql-password: {{ .Values.secret.mysqlPassword }}
  mysql-database: {{ .Values.secret.mysqlDatabase }}
  mysql-host: {{ .Values.secret.mysqlHost }}

