apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-user: YWRtaW4=
  mysql-password: d29yZHByZXNzMTIz
  mysql-database: d29yZHByZXNz
  mysql-host: aGFkaXlhLXdvcmRwcmVzcy1kYi5jam8yZ3ltb2Fxb20uYXAtc291dGgtMS5yZHMuYW1hem9uYXdzLmNvbQ==

