apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-user: YWRtaW4=
  mysql-password: RGF0YWJhc2UxMjM=
  mysql-database: dGVkeGRi
  mysql-host: aGFkaXlhLWRiLXBvYy0xLmNqdWsyNnl3MmN0OC5hcC1zb3V0aC0xLnJkcy5hbWF6b25hd3MuY29t 

